---
development:
  cloud_name: trunghc
  api_key: '845512117941652'
  api_secret: VcxY6jo3U44p2HIu7hypCLgI9bE
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: trunghc
  api_key: '845512117941652'
  api_secret: VcxY6jo3U44p2HIu7hypCLgI9bE
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: trunghc
  api_key: '845512117941652'
  api_secret: VcxY6jo3U44p2HIu7hypCLgI9bE
  enhance_image_tag: true
  static_image_support: false
